// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bridge/v1beta/ethereum_to_pools.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	github_com_ethereum_go_ethereum_common "github.com/ethereum/go-ethereum/common"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DelegateVote struct {
	Nonce     uint64                                          `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Delegator *github_com_ethereum_go_ethereum_common.Address `protobuf:"bytes,2,opt,name=delegator,proto3,casttype=github.com/ethereum/go-ethereum/common.Address" json:"delegator,omitempty"`
	To        *github_com_ethereum_go_ethereum_common.Address `protobuf:"bytes,3,opt,name=to,proto3,casttype=github.com/ethereum/go-ethereum/common.Address" json:"to,omitempty"`
	Power     uint64                                          `protobuf:"varint,4,opt,name=power,proto3" json:"power,omitempty"`
}

func (m *DelegateVote) Reset()         { *m = DelegateVote{} }
func (m *DelegateVote) String() string { return proto.CompactTextString(m) }
func (*DelegateVote) ProtoMessage()    {}
func (*DelegateVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fc670358116c6e3, []int{0}
}
func (m *DelegateVote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DelegateVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DelegateVote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DelegateVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegateVote.Merge(m, src)
}
func (m *DelegateVote) XXX_Size() int {
	return m.Size()
}
func (m *DelegateVote) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegateVote.DiscardUnknown(m)
}

var xxx_messageInfo_DelegateVote proto.InternalMessageInfo

func (m *DelegateVote) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *DelegateVote) GetDelegator() *github_com_ethereum_go_ethereum_common.Address {
	if m != nil {
		return m.Delegator
	}
	return nil
}

func (m *DelegateVote) GetTo() *github_com_ethereum_go_ethereum_common.Address {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *DelegateVote) GetPower() uint64 {
	if m != nil {
		return m.Power
	}
	return 0
}

type UnDelegateVote struct {
	Nonce     uint64                                          `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	From      *github_com_ethereum_go_ethereum_common.Address `protobuf:"bytes,2,opt,name=from,proto3,casttype=github.com/ethereum/go-ethereum/common.Address" json:"from,omitempty"`
	Delegator *github_com_ethereum_go_ethereum_common.Address `protobuf:"bytes,3,opt,name=delegator,proto3,casttype=github.com/ethereum/go-ethereum/common.Address" json:"delegator,omitempty"`
}

func (m *UnDelegateVote) Reset()         { *m = UnDelegateVote{} }
func (m *UnDelegateVote) String() string { return proto.CompactTextString(m) }
func (*UnDelegateVote) ProtoMessage()    {}
func (*UnDelegateVote) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fc670358116c6e3, []int{1}
}
func (m *UnDelegateVote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UnDelegateVote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UnDelegateVote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UnDelegateVote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnDelegateVote.Merge(m, src)
}
func (m *UnDelegateVote) XXX_Size() int {
	return m.Size()
}
func (m *UnDelegateVote) XXX_DiscardUnknown() {
	xxx_messageInfo_UnDelegateVote.DiscardUnknown(m)
}

var xxx_messageInfo_UnDelegateVote proto.InternalMessageInfo

func (m *UnDelegateVote) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *UnDelegateVote) GetFrom() *github_com_ethereum_go_ethereum_common.Address {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *UnDelegateVote) GetDelegator() *github_com_ethereum_go_ethereum_common.Address {
	if m != nil {
		return m.Delegator
	}
	return nil
}

type CreatePool struct {
	Nonce uint64 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (m *CreatePool) Reset()         { *m = CreatePool{} }
func (m *CreatePool) String() string { return proto.CompactTextString(m) }
func (*CreatePool) ProtoMessage()    {}
func (*CreatePool) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fc670358116c6e3, []int{2}
}
func (m *CreatePool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreatePool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreatePool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreatePool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePool.Merge(m, src)
}
func (m *CreatePool) XXX_Size() int {
	return m.Size()
}
func (m *CreatePool) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePool.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePool proto.InternalMessageInfo

func (m *CreatePool) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type CreateValidator struct {
	Nonce           uint64                                          `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	EthereumAddress *github_com_ethereum_go_ethereum_common.Address `protobuf:"bytes,2,opt,name=ethereum_address,json=ethereumAddress,proto3,casttype=github.com/ethereum/go-ethereum/common.Address" json:"ethereum_address,omitempty"`
	ConsensusPubkey *github_com_cosmos_cosmos_sdk_types.AccAddress  `protobuf:"bytes,3,opt,name=consensus_pubkey,json=consensusPubkey,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"consensus_pubkey,omitempty"`
	EthStake        uint64                                          `protobuf:"varint,4,opt,name=eth_stake,json=ethStake,proto3" json:"eth_stake,omitempty"`
}

func (m *CreateValidator) Reset()         { *m = CreateValidator{} }
func (m *CreateValidator) String() string { return proto.CompactTextString(m) }
func (*CreateValidator) ProtoMessage()    {}
func (*CreateValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fc670358116c6e3, []int{3}
}
func (m *CreateValidator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateValidator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateValidator.Merge(m, src)
}
func (m *CreateValidator) XXX_Size() int {
	return m.Size()
}
func (m *CreateValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateValidator.DiscardUnknown(m)
}

var xxx_messageInfo_CreateValidator proto.InternalMessageInfo

func (m *CreateValidator) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *CreateValidator) GetEthereumAddress() *github_com_ethereum_go_ethereum_common.Address {
	if m != nil {
		return m.EthereumAddress
	}
	return nil
}

func (m *CreateValidator) GetConsensusPubkey() *github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.ConsensusPubkey
	}
	return nil
}

func (m *CreateValidator) GetEthStake() uint64 {
	if m != nil {
		return m.EthStake
	}
	return 0
}

type UpdateValidator struct {
	Nonce              uint64                                          `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ConsensusPubkey    *github_com_cosmos_cosmos_sdk_types.AccAddress  `protobuf:"bytes,2,opt,name=consensus_pubkey,json=consensusPubkey,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"consensus_pubkey,omitempty"`
	NewEthereumAddress *github_com_ethereum_go_ethereum_common.Address `protobuf:"bytes,3,opt,name=new_ethereum_address,json=newEthereumAddress,proto3,casttype=github.com/ethereum/go-ethereum/common.Address" json:"new_ethereum_address,omitempty"`
	NewEthStake        uint64                                          `protobuf:"varint,4,opt,name=new_eth_stake,json=newEthStake,proto3" json:"new_eth_stake,omitempty"`
	Exit               bool                                            `protobuf:"varint,5,opt,name=exit,proto3" json:"exit,omitempty"`
}

func (m *UpdateValidator) Reset()         { *m = UpdateValidator{} }
func (m *UpdateValidator) String() string { return proto.CompactTextString(m) }
func (*UpdateValidator) ProtoMessage()    {}
func (*UpdateValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fc670358116c6e3, []int{4}
}
func (m *UpdateValidator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateValidator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdateValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateValidator.Merge(m, src)
}
func (m *UpdateValidator) XXX_Size() int {
	return m.Size()
}
func (m *UpdateValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateValidator.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateValidator proto.InternalMessageInfo

func (m *UpdateValidator) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *UpdateValidator) GetConsensusPubkey() *github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.ConsensusPubkey
	}
	return nil
}

func (m *UpdateValidator) GetNewEthereumAddress() *github_com_ethereum_go_ethereum_common.Address {
	if m != nil {
		return m.NewEthereumAddress
	}
	return nil
}

func (m *UpdateValidator) GetNewEthStake() uint64 {
	if m != nil {
		return m.NewEthStake
	}
	return 0
}

func (m *UpdateValidator) GetExit() bool {
	if m != nil {
		return m.Exit
	}
	return false
}

// MsgEthereumClaim is a container for events that happened on the ethereum blockchain.
// It's essentially an ethereum -> pools oracle
// each event has nonce, a monotonic id of the claim
// Due to eth1 probabilistic finality, each validator on the pools network will need to attest to all claims to make them be included in the state (2/3 vote).
type MsgEthereumClaim struct {
	EthereumChainId  uint64                                          `protobuf:"varint,1,opt,name=ethereum_chain_id,json=ethereumChainId,proto3" json:"ethereum_chain_id,omitempty"`
	ContractAddress  *github_com_ethereum_go_ethereum_common.Address `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3,casttype=github.com/ethereum/go-ethereum/common.Address" json:"contract_address,omitempty"`
	ConsensusPubkey  *github_com_cosmos_cosmos_sdk_types.AccAddress  `protobuf:"bytes,3,opt,name=consensus_pubkey,json=consensusPubkey,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"consensus_pubkey,omitempty"`
	Delegates        []*DelegateVote                                 `protobuf:"bytes,4,rep,name=delegates,proto3" json:"delegates,omitempty"`
	Undelegates      []*UnDelegateVote                               `protobuf:"bytes,5,rep,name=undelegates,proto3" json:"undelegates,omitempty"`
	CreatePools      []*CreatePool                                   `protobuf:"bytes,6,rep,name=create_pools,json=createPools,proto3" json:"create_pools,omitempty"`
	CreateValidators []*CreateValidator                              `protobuf:"bytes,7,rep,name=create_validators,json=createValidators,proto3" json:"create_validators,omitempty"`
	UpdateValidators []*UpdateValidator                              `protobuf:"bytes,8,rep,name=update_validators,json=updateValidators,proto3" json:"update_validators,omitempty"`
}

func (m *MsgEthereumClaim) Reset()         { *m = MsgEthereumClaim{} }
func (m *MsgEthereumClaim) String() string { return proto.CompactTextString(m) }
func (*MsgEthereumClaim) ProtoMessage()    {}
func (*MsgEthereumClaim) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fc670358116c6e3, []int{5}
}
func (m *MsgEthereumClaim) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEthereumClaim) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEthereumClaim.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEthereumClaim) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEthereumClaim.Merge(m, src)
}
func (m *MsgEthereumClaim) XXX_Size() int {
	return m.Size()
}
func (m *MsgEthereumClaim) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEthereumClaim.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEthereumClaim proto.InternalMessageInfo

func (m *MsgEthereumClaim) GetEthereumChainId() uint64 {
	if m != nil {
		return m.EthereumChainId
	}
	return 0
}

func (m *MsgEthereumClaim) GetContractAddress() *github_com_ethereum_go_ethereum_common.Address {
	if m != nil {
		return m.ContractAddress
	}
	return nil
}

func (m *MsgEthereumClaim) GetConsensusPubkey() *github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.ConsensusPubkey
	}
	return nil
}

func (m *MsgEthereumClaim) GetDelegates() []*DelegateVote {
	if m != nil {
		return m.Delegates
	}
	return nil
}

func (m *MsgEthereumClaim) GetUndelegates() []*UnDelegateVote {
	if m != nil {
		return m.Undelegates
	}
	return nil
}

func (m *MsgEthereumClaim) GetCreatePools() []*CreatePool {
	if m != nil {
		return m.CreatePools
	}
	return nil
}

func (m *MsgEthereumClaim) GetCreateValidators() []*CreateValidator {
	if m != nil {
		return m.CreateValidators
	}
	return nil
}

func (m *MsgEthereumClaim) GetUpdateValidators() []*UpdateValidator {
	if m != nil {
		return m.UpdateValidators
	}
	return nil
}

func init() {
	proto.RegisterType((*DelegateVote)(nil), "bridge.v1beta1.DelegateVote")
	proto.RegisterType((*UnDelegateVote)(nil), "bridge.v1beta1.UnDelegateVote")
	proto.RegisterType((*CreatePool)(nil), "bridge.v1beta1.CreatePool")
	proto.RegisterType((*CreateValidator)(nil), "bridge.v1beta1.CreateValidator")
	proto.RegisterType((*UpdateValidator)(nil), "bridge.v1beta1.UpdateValidator")
	proto.RegisterType((*MsgEthereumClaim)(nil), "bridge.v1beta1.MsgEthereumClaim")
}

func init() {
	proto.RegisterFile("bridge/v1beta/ethereum_to_pools.proto", fileDescriptor_1fc670358116c6e3)
}

var fileDescriptor_1fc670358116c6e3 = []byte{
	// 658 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xcd, 0x6a, 0xdb, 0x4e,
	0x10, 0x8f, 0x1c, 0x3b, 0xff, 0x64, 0x9d, 0x7f, 0xe2, 0x2c, 0x3e, 0xa8, 0x69, 0x71, 0x8c, 0xa0,
	0x60, 0x0a, 0x96, 0x48, 0x7a, 0x2b, 0x14, 0x9a, 0xa4, 0x3d, 0x04, 0x5a, 0x08, 0x2a, 0x09, 0xa5,
	0x14, 0x8c, 0xb4, 0x9a, 0xc8, 0xc2, 0xd2, 0x8e, 0xd0, 0xae, 0xe2, 0xb8, 0xa7, 0x3e, 0x42, 0x5f,
	0xa4, 0xef, 0xd1, 0x5b, 0x73, 0xec, 0x29, 0x94, 0xe4, 0xda, 0x27, 0x08, 0x3d, 0x14, 0xaf, 0x64,
	0xf9, 0xa3, 0xa6, 0xe4, 0xe0, 0xd0, 0x93, 0x76, 0x46, 0x33, 0xbf, 0xd9, 0xf9, 0xcd, 0xc7, 0x92,
	0xc7, 0x6e, 0x12, 0x78, 0x3e, 0x58, 0xe7, 0xbb, 0x2e, 0x48, 0xc7, 0x02, 0xd9, 0x85, 0x04, 0xd2,
	0xa8, 0x23, 0xb1, 0x13, 0x23, 0x86, 0xc2, 0x8c, 0x13, 0x94, 0x48, 0x37, 0x32, 0x33, 0x33, 0x33,
	0xdb, 0xdd, 0xae, 0xfb, 0xe8, 0xa3, 0xfa, 0x65, 0x0d, 0x4f, 0x99, 0xd5, 0xf6, 0x03, 0x1f, 0xd1,
	0x0f, 0xc1, 0x52, 0x92, 0x9b, 0x9e, 0x59, 0x0e, 0x1f, 0x64, 0xbf, 0x8c, 0x5f, 0x1a, 0x59, 0x7f,
	0x09, 0x21, 0xf8, 0x8e, 0x84, 0x53, 0x94, 0x40, 0xeb, 0xa4, 0xc2, 0x91, 0x33, 0xd0, 0xb5, 0xa6,
	0xd6, 0x2a, 0xdb, 0x99, 0x40, 0xcf, 0xc8, 0x9a, 0x97, 0x59, 0x61, 0xa2, 0x97, 0x9a, 0x5a, 0xab,
	0xba, 0x57, 0x37, 0x33, 0x54, 0x73, 0x84, 0x6a, 0xee, 0xf3, 0xc1, 0xc1, 0xde, 0xed, 0xd5, 0x8e,
	0xe9, 0x07, 0xb2, 0x9b, 0xba, 0x26, 0xc3, 0xa8, 0xb8, 0xb8, 0xe5, 0x63, 0xbb, 0x38, 0x33, 0x8c,
	0x22, 0xe4, 0xe6, 0xbe, 0xe7, 0x25, 0x20, 0x84, 0x3d, 0x86, 0xa6, 0xef, 0x48, 0x49, 0xa2, 0xbe,
	0xbc, 0xe0, 0x00, 0x25, 0x89, 0xc3, 0xbc, 0x62, 0xec, 0x43, 0xa2, 0x97, 0xb3, 0xbc, 0x94, 0x60,
	0xfc, 0xd4, 0xc8, 0xc6, 0x09, 0xbf, 0x03, 0x01, 0x1f, 0x48, 0xf9, 0x2c, 0xc1, 0x68, 0xe1, 0xb9,
	0x2b, 0xd4, 0x69, 0x7a, 0x97, 0xef, 0x8d, 0x5e, 0xc3, 0x20, 0xe4, 0x30, 0x01, 0x47, 0xc2, 0x31,
	0x62, 0x38, 0x3f, 0x53, 0xe3, 0x4b, 0x89, 0x6c, 0x66, 0x46, 0xa7, 0x4e, 0x18, 0x78, 0xaa, 0x2c,
	0xf3, 0x39, 0x11, 0xa4, 0x56, 0xf4, 0xa5, 0x93, 0x05, 0x5b, 0x38, 0x3f, 0x9b, 0xa3, 0x1f, 0xb9,
	0x82, 0x26, 0xa4, 0xc6, 0x90, 0x0b, 0xe0, 0x22, 0x15, 0x9d, 0x38, 0x75, 0x7b, 0x30, 0xf8, 0x2b,
	0x63, 0xbb, 0xb7, 0x57, 0x3b, 0xed, 0x89, 0xa0, 0x0c, 0x45, 0x84, 0x22, 0xff, 0xb4, 0x85, 0xd7,
	0xb3, 0xe4, 0x20, 0x06, 0x61, 0xee, 0x33, 0x56, 0xc4, 0x2c, 0x02, 0x1c, 0x2b, 0x7c, 0xfa, 0x90,
	0xac, 0x81, 0xec, 0x76, 0x84, 0x74, 0x7a, 0x90, 0xf7, 0xcf, 0x2a, 0xc8, 0xee, 0xdb, 0xa1, 0x6c,
	0x7c, 0x2b, 0x91, 0xcd, 0x93, 0xd8, 0xbb, 0x03, 0x5f, 0xf3, 0xae, 0x5e, 0xba, 0xe7, 0xab, 0x7f,
	0x24, 0x75, 0x0e, 0xfd, 0xce, 0x1f, 0x75, 0x5a, 0x74, 0x93, 0x51, 0x0e, 0xfd, 0x57, 0x33, 0xa5,
	0x32, 0xc8, 0xff, 0x79, 0xec, 0x29, 0xea, 0xaa, 0x99, 0xa9, 0x62, 0x8f, 0x52, 0x52, 0x86, 0x8b,
	0x40, 0xea, 0x95, 0xa6, 0xd6, 0x5a, 0xb5, 0xd5, 0xd9, 0xf8, 0x54, 0x21, 0xb5, 0x37, 0xc2, 0x1f,
	0xc1, 0x1d, 0x86, 0x4e, 0x10, 0xd1, 0x27, 0x64, 0xab, 0x48, 0x82, 0x75, 0x9d, 0x80, 0x77, 0x02,
	0x2f, 0xa7, 0xb7, 0xe8, 0x91, 0xc3, 0xa1, 0xfe, 0xc8, 0x1b, 0x36, 0x26, 0x43, 0x2e, 0x13, 0x87,
	0xc9, 0xfb, 0x6b, 0xcc, 0x51, 0x84, 0x7f, 0xd9, 0x98, 0xcf, 0x8a, 0xbd, 0x01, 0x42, 0x2f, 0x37,
	0x97, 0x5b, 0xd5, 0xbd, 0x47, 0xe6, 0xf4, 0x93, 0x60, 0x4e, 0x2e, 0x37, 0x7b, 0x6c, 0x4e, 0x5f,
	0x90, 0x6a, 0xca, 0xc7, 0xde, 0x15, 0xe5, 0xdd, 0x98, 0xf5, 0x9e, 0x5e, 0x8e, 0xf6, 0xa4, 0x0b,
	0x7d, 0x4e, 0xd6, 0x99, 0x5a, 0x14, 0xd9, 0x93, 0xa4, 0xaf, 0x28, 0x88, 0xed, 0x59, 0x88, 0xf1,
	0xc6, 0xb1, 0xab, 0xac, 0x38, 0x0b, 0xfa, 0x9a, 0x6c, 0xe5, 0xee, 0xe7, 0xa3, 0xc1, 0x11, 0xfa,
	0x7f, 0x0a, 0x63, 0x67, 0x3e, 0x46, 0x31, 0x60, 0x76, 0x8d, 0x4d, 0x2b, 0x14, 0x5a, 0xaa, 0xa6,
	0x70, 0x12, 0x6d, 0x75, 0x3e, 0xda, 0xcc, 0xb8, 0xda, 0xb5, 0x74, 0x5a, 0x21, 0x0e, 0x8e, 0xbe,
	0x5e, 0x37, 0xb4, 0xcb, 0xeb, 0x86, 0xf6, 0xe3, 0xba, 0xa1, 0x7d, 0xbe, 0x69, 0x2c, 0x5d, 0xde,
	0x34, 0x96, 0xbe, 0xdf, 0x34, 0x96, 0xde, 0x5b, 0x13, 0x25, 0x73, 0x43, 0xbc, 0x70, 0xe2, 0xd8,
	0x52, 0xe9, 0xb7, 0x39, 0xc8, 0x3e, 0x26, 0x3d, 0xeb, 0xc2, 0xca, 0xdf, 0x6e, 0x55, 0x3f, 0x77,
	0x45, 0x55, 0xfd, 0xe9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x12, 0x00, 0x4d, 0xd2, 0x07,
	0x00, 0x00,
}

func (m *DelegateVote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DelegateVote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DelegateVote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Power != 0 {
		i = encodeVarintEthereumToPools(dAtA, i, uint64(m.Power))
		i--
		dAtA[i] = 0x20
	}
	if m.To != nil {
		{
			size, err := m.To.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEthereumToPools(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Delegator != nil {
		{
			size, err := m.Delegator.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEthereumToPools(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Nonce != 0 {
		i = encodeVarintEthereumToPools(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *UnDelegateVote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UnDelegateVote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UnDelegateVote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Delegator != nil {
		{
			size, err := m.Delegator.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEthereumToPools(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.From != nil {
		{
			size, err := m.From.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEthereumToPools(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Nonce != 0 {
		i = encodeVarintEthereumToPools(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CreatePool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreatePool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreatePool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Nonce != 0 {
		i = encodeVarintEthereumToPools(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CreateValidator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateValidator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateValidator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EthStake != 0 {
		i = encodeVarintEthereumToPools(dAtA, i, uint64(m.EthStake))
		i--
		dAtA[i] = 0x20
	}
	if m.ConsensusPubkey != nil {
		{
			size, err := m.ConsensusPubkey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEthereumToPools(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.EthereumAddress != nil {
		{
			size, err := m.EthereumAddress.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEthereumToPools(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Nonce != 0 {
		i = encodeVarintEthereumToPools(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *UpdateValidator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateValidator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UpdateValidator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Exit {
		i--
		if m.Exit {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.NewEthStake != 0 {
		i = encodeVarintEthereumToPools(dAtA, i, uint64(m.NewEthStake))
		i--
		dAtA[i] = 0x20
	}
	if m.NewEthereumAddress != nil {
		{
			size, err := m.NewEthereumAddress.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEthereumToPools(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.ConsensusPubkey != nil {
		{
			size, err := m.ConsensusPubkey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEthereumToPools(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Nonce != 0 {
		i = encodeVarintEthereumToPools(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgEthereumClaim) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEthereumClaim) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEthereumClaim) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UpdateValidators) > 0 {
		for iNdEx := len(m.UpdateValidators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UpdateValidators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEthereumToPools(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.CreateValidators) > 0 {
		for iNdEx := len(m.CreateValidators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CreateValidators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEthereumToPools(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.CreatePools) > 0 {
		for iNdEx := len(m.CreatePools) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CreatePools[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEthereumToPools(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Undelegates) > 0 {
		for iNdEx := len(m.Undelegates) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Undelegates[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEthereumToPools(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Delegates) > 0 {
		for iNdEx := len(m.Delegates) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Delegates[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEthereumToPools(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.ConsensusPubkey != nil {
		{
			size, err := m.ConsensusPubkey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEthereumToPools(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.ContractAddress != nil {
		{
			size, err := m.ContractAddress.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEthereumToPools(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.EthereumChainId != 0 {
		i = encodeVarintEthereumToPools(dAtA, i, uint64(m.EthereumChainId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintEthereumToPools(dAtA []byte, offset int, v uint64) int {
	offset -= sovEthereumToPools(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DelegateVote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Nonce != 0 {
		n += 1 + sovEthereumToPools(uint64(m.Nonce))
	}
	if m.Delegator != nil {
		l = m.Delegator.Size()
		n += 1 + l + sovEthereumToPools(uint64(l))
	}
	if m.To != nil {
		l = m.To.Size()
		n += 1 + l + sovEthereumToPools(uint64(l))
	}
	if m.Power != 0 {
		n += 1 + sovEthereumToPools(uint64(m.Power))
	}
	return n
}

func (m *UnDelegateVote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Nonce != 0 {
		n += 1 + sovEthereumToPools(uint64(m.Nonce))
	}
	if m.From != nil {
		l = m.From.Size()
		n += 1 + l + sovEthereumToPools(uint64(l))
	}
	if m.Delegator != nil {
		l = m.Delegator.Size()
		n += 1 + l + sovEthereumToPools(uint64(l))
	}
	return n
}

func (m *CreatePool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Nonce != 0 {
		n += 1 + sovEthereumToPools(uint64(m.Nonce))
	}
	return n
}

func (m *CreateValidator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Nonce != 0 {
		n += 1 + sovEthereumToPools(uint64(m.Nonce))
	}
	if m.EthereumAddress != nil {
		l = m.EthereumAddress.Size()
		n += 1 + l + sovEthereumToPools(uint64(l))
	}
	if m.ConsensusPubkey != nil {
		l = m.ConsensusPubkey.Size()
		n += 1 + l + sovEthereumToPools(uint64(l))
	}
	if m.EthStake != 0 {
		n += 1 + sovEthereumToPools(uint64(m.EthStake))
	}
	return n
}

func (m *UpdateValidator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Nonce != 0 {
		n += 1 + sovEthereumToPools(uint64(m.Nonce))
	}
	if m.ConsensusPubkey != nil {
		l = m.ConsensusPubkey.Size()
		n += 1 + l + sovEthereumToPools(uint64(l))
	}
	if m.NewEthereumAddress != nil {
		l = m.NewEthereumAddress.Size()
		n += 1 + l + sovEthereumToPools(uint64(l))
	}
	if m.NewEthStake != 0 {
		n += 1 + sovEthereumToPools(uint64(m.NewEthStake))
	}
	if m.Exit {
		n += 2
	}
	return n
}

func (m *MsgEthereumClaim) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EthereumChainId != 0 {
		n += 1 + sovEthereumToPools(uint64(m.EthereumChainId))
	}
	if m.ContractAddress != nil {
		l = m.ContractAddress.Size()
		n += 1 + l + sovEthereumToPools(uint64(l))
	}
	if m.ConsensusPubkey != nil {
		l = m.ConsensusPubkey.Size()
		n += 1 + l + sovEthereumToPools(uint64(l))
	}
	if len(m.Delegates) > 0 {
		for _, e := range m.Delegates {
			l = e.Size()
			n += 1 + l + sovEthereumToPools(uint64(l))
		}
	}
	if len(m.Undelegates) > 0 {
		for _, e := range m.Undelegates {
			l = e.Size()
			n += 1 + l + sovEthereumToPools(uint64(l))
		}
	}
	if len(m.CreatePools) > 0 {
		for _, e := range m.CreatePools {
			l = e.Size()
			n += 1 + l + sovEthereumToPools(uint64(l))
		}
	}
	if len(m.CreateValidators) > 0 {
		for _, e := range m.CreateValidators {
			l = e.Size()
			n += 1 + l + sovEthereumToPools(uint64(l))
		}
	}
	if len(m.UpdateValidators) > 0 {
		for _, e := range m.UpdateValidators {
			l = e.Size()
			n += 1 + l + sovEthereumToPools(uint64(l))
		}
	}
	return n
}

func sovEthereumToPools(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEthereumToPools(x uint64) (n int) {
	return sovEthereumToPools(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DelegateVote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEthereumToPools
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DelegateVote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DelegateVote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Delegator == nil {
				m.Delegator = &github_com_ethereum_go_ethereum_common.Address{}
			}
			if err := m.Delegator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.To == nil {
				m.To = &github_com_ethereum_go_ethereum_common.Address{}
			}
			if err := m.To.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Power", wireType)
			}
			m.Power = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Power |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEthereumToPools(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UnDelegateVote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEthereumToPools
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UnDelegateVote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UnDelegateVote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.From == nil {
				m.From = &github_com_ethereum_go_ethereum_common.Address{}
			}
			if err := m.From.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Delegator == nil {
				m.Delegator = &github_com_ethereum_go_ethereum_common.Address{}
			}
			if err := m.Delegator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEthereumToPools(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreatePool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEthereumToPools
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreatePool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreatePool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEthereumToPools(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateValidator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEthereumToPools
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateValidator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateValidator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthereumAddress", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EthereumAddress == nil {
				m.EthereumAddress = &github_com_ethereum_go_ethereum_common.Address{}
			}
			if err := m.EthereumAddress.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusPubkey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConsensusPubkey == nil {
				m.ConsensusPubkey = &github_com_cosmos_cosmos_sdk_types.AccAddress{}
			}
			if err := m.ConsensusPubkey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthStake", wireType)
			}
			m.EthStake = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EthStake |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEthereumToPools(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateValidator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEthereumToPools
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateValidator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateValidator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusPubkey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConsensusPubkey == nil {
				m.ConsensusPubkey = &github_com_cosmos_cosmos_sdk_types.AccAddress{}
			}
			if err := m.ConsensusPubkey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewEthereumAddress", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NewEthereumAddress == nil {
				m.NewEthereumAddress = &github_com_ethereum_go_ethereum_common.Address{}
			}
			if err := m.NewEthereumAddress.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewEthStake", wireType)
			}
			m.NewEthStake = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NewEthStake |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exit", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Exit = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipEthereumToPools(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgEthereumClaim) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEthereumToPools
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEthereumClaim: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEthereumClaim: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthereumChainId", wireType)
			}
			m.EthereumChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EthereumChainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ContractAddress == nil {
				m.ContractAddress = &github_com_ethereum_go_ethereum_common.Address{}
			}
			if err := m.ContractAddress.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusPubkey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConsensusPubkey == nil {
				m.ConsensusPubkey = &github_com_cosmos_cosmos_sdk_types.AccAddress{}
			}
			if err := m.ConsensusPubkey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegates = append(m.Delegates, &DelegateVote{})
			if err := m.Delegates[len(m.Delegates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Undelegates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Undelegates = append(m.Undelegates, &UnDelegateVote{})
			if err := m.Undelegates[len(m.Undelegates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatePools", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatePools = append(m.CreatePools, &CreatePool{})
			if err := m.CreatePools[len(m.CreatePools)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateValidators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreateValidators = append(m.CreateValidators, &CreateValidator{})
			if err := m.CreateValidators[len(m.CreateValidators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateValidators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdateValidators = append(m.UpdateValidators, &UpdateValidator{})
			if err := m.UpdateValidators[len(m.UpdateValidators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEthereumToPools(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthEthereumToPools
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEthereumToPools(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEthereumToPools
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEthereumToPools
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEthereumToPools
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEthereumToPools
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEthereumToPools
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEthereumToPools        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEthereumToPools          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEthereumToPools = fmt.Errorf("proto: unexpected end of group")
)
