// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bridge/v1beta/pools_to_ethereum.proto

package types

import (
	fmt "fmt"
	github_com_bloxapp_pools_network_shared_types "github.com/bloxapp/pools-network/shared/types"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ValSetChange struct {
	Address  *github_com_bloxapp_pools_network_shared_types.EthereumAddress `protobuf:"bytes,1,opt,name=address,proto3,customtype=github.com/bloxapp/pools-network/shared/types.EthereumAddress" json:"address,omitempty"`
	NewPower uint64                                                         `protobuf:"varint,2,opt,name=new_power,json=newPower,proto3" json:"new_power,omitempty"`
}

func (m *ValSetChange) Reset()         { *m = ValSetChange{} }
func (m *ValSetChange) String() string { return proto.CompactTextString(m) }
func (*ValSetChange) ProtoMessage()    {}
func (*ValSetChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc300e9b99542c6a, []int{0}
}
func (m *ValSetChange) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValSetChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValSetChange.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValSetChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValSetChange.Merge(m, src)
}
func (m *ValSetChange) XXX_Size() int {
	return m.Size()
}
func (m *ValSetChange) XXX_DiscardUnknown() {
	xxx_messageInfo_ValSetChange.DiscardUnknown(m)
}

var xxx_messageInfo_ValSetChange proto.InternalMessageInfo

func (m *ValSetChange) GetNewPower() uint64 {
	if m != nil {
		return m.NewPower
	}
	return 0
}

type ETHBalanceChange struct {
	TotalEth uint64 `protobuf:"varint,1,opt,name=total_eth,json=totalEth,proto3" json:"total_eth,omitempty"`
}

func (m *ETHBalanceChange) Reset()         { *m = ETHBalanceChange{} }
func (m *ETHBalanceChange) String() string { return proto.CompactTextString(m) }
func (*ETHBalanceChange) ProtoMessage()    {}
func (*ETHBalanceChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc300e9b99542c6a, []int{1}
}
func (m *ETHBalanceChange) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ETHBalanceChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ETHBalanceChange.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ETHBalanceChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ETHBalanceChange.Merge(m, src)
}
func (m *ETHBalanceChange) XXX_Size() int {
	return m.Size()
}
func (m *ETHBalanceChange) XXX_DiscardUnknown() {
	xxx_messageInfo_ETHBalanceChange.DiscardUnknown(m)
}

var xxx_messageInfo_ETHBalanceChange proto.InternalMessageInfo

func (m *ETHBalanceChange) GetTotalEth() uint64 {
	if m != nil {
		return m.TotalEth
	}
	return 0
}

type Withdraw struct {
	To          []byte                                                         `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Amount      uint64                                                         `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	CoinAddress *github_com_bloxapp_pools_network_shared_types.EthereumAddress `protobuf:"bytes,3,opt,name=coin_address,json=coinAddress,proto3,customtype=github.com/bloxapp/pools-network/shared/types.EthereumAddress" json:"coin_address,omitempty"`
}

func (m *Withdraw) Reset()         { *m = Withdraw{} }
func (m *Withdraw) String() string { return proto.CompactTextString(m) }
func (*Withdraw) ProtoMessage()    {}
func (*Withdraw) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc300e9b99542c6a, []int{2}
}
func (m *Withdraw) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Withdraw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Withdraw.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Withdraw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Withdraw.Merge(m, src)
}
func (m *Withdraw) XXX_Size() int {
	return m.Size()
}
func (m *Withdraw) XXX_DiscardUnknown() {
	xxx_messageInfo_Withdraw.DiscardUnknown(m)
}

var xxx_messageInfo_Withdraw proto.InternalMessageInfo

func (m *Withdraw) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Withdraw) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

// nonce is the monotonic id of an update
type MsgBridgedUpdate struct {
	Nonce        uint64            `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ValSetChange []*ValSetChange   `protobuf:"bytes,2,rep,name=val_set_change,json=valSetChange,proto3" json:"val_set_change,omitempty"`
	NewBalance   *ETHBalanceChange `protobuf:"bytes,3,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	Withdrawals  []*Withdraw       `protobuf:"bytes,4,rep,name=withdrawals,proto3" json:"withdrawals,omitempty"`
}

func (m *MsgBridgedUpdate) Reset()         { *m = MsgBridgedUpdate{} }
func (m *MsgBridgedUpdate) String() string { return proto.CompactTextString(m) }
func (*MsgBridgedUpdate) ProtoMessage()    {}
func (*MsgBridgedUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc300e9b99542c6a, []int{3}
}
func (m *MsgBridgedUpdate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBridgedUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBridgedUpdate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBridgedUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBridgedUpdate.Merge(m, src)
}
func (m *MsgBridgedUpdate) XXX_Size() int {
	return m.Size()
}
func (m *MsgBridgedUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBridgedUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBridgedUpdate proto.InternalMessageInfo

func (m *MsgBridgedUpdate) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *MsgBridgedUpdate) GetValSetChange() []*ValSetChange {
	if m != nil {
		return m.ValSetChange
	}
	return nil
}

func (m *MsgBridgedUpdate) GetNewBalance() *ETHBalanceChange {
	if m != nil {
		return m.NewBalance
	}
	return nil
}

func (m *MsgBridgedUpdate) GetWithdrawals() []*Withdraw {
	if m != nil {
		return m.Withdrawals
	}
	return nil
}

// MsgBridgedUpdateConfirm is a signed container for a bridged update (pools -> ethereum).
// This is a single operator's signatur.
// nonce is the monotonic id of an update
type MsgBridgedUpdateConfirm struct {
	Nonce           uint64                                                         `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature       []byte                                                         `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	EthereumAddress *github_com_bloxapp_pools_network_shared_types.EthereumAddress `protobuf:"bytes,3,opt,name=ethereum_address,json=ethereumAddress,proto3,customtype=github.com/bloxapp/pools-network/shared/types.EthereumAddress" json:"ethereum_address,omitempty"`
}

func (m *MsgBridgedUpdateConfirm) Reset()         { *m = MsgBridgedUpdateConfirm{} }
func (m *MsgBridgedUpdateConfirm) String() string { return proto.CompactTextString(m) }
func (*MsgBridgedUpdateConfirm) ProtoMessage()    {}
func (*MsgBridgedUpdateConfirm) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc300e9b99542c6a, []int{4}
}
func (m *MsgBridgedUpdateConfirm) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBridgedUpdateConfirm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBridgedUpdateConfirm.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBridgedUpdateConfirm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBridgedUpdateConfirm.Merge(m, src)
}
func (m *MsgBridgedUpdateConfirm) XXX_Size() int {
	return m.Size()
}
func (m *MsgBridgedUpdateConfirm) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBridgedUpdateConfirm.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBridgedUpdateConfirm proto.InternalMessageInfo

func (m *MsgBridgedUpdateConfirm) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *MsgBridgedUpdateConfirm) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*ValSetChange)(nil), "bridge.v1beta1.ValSetChange")
	proto.RegisterType((*ETHBalanceChange)(nil), "bridge.v1beta1.ETHBalanceChange")
	proto.RegisterType((*Withdraw)(nil), "bridge.v1beta1.Withdraw")
	proto.RegisterType((*MsgBridgedUpdate)(nil), "bridge.v1beta1.MsgBridgedUpdate")
	proto.RegisterType((*MsgBridgedUpdateConfirm)(nil), "bridge.v1beta1.MsgBridgedUpdateConfirm")
}

func init() {
	proto.RegisterFile("bridge/v1beta/pools_to_ethereum.proto", fileDescriptor_bc300e9b99542c6a)
}

var fileDescriptor_bc300e9b99542c6a = []byte{
	// 510 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x4f, 0x8b, 0xd3, 0x40,
	0x14, 0xdf, 0xe9, 0xd6, 0xb5, 0x9d, 0x96, 0x5a, 0x86, 0xa2, 0x75, 0x77, 0x89, 0xa5, 0x20, 0xf4,
	0x62, 0x86, 0x5d, 0x6f, 0x82, 0x87, 0x76, 0x29, 0xe8, 0x41, 0x90, 0xf8, 0x0f, 0xbc, 0x84, 0x49,
	0xf3, 0x36, 0x09, 0xa6, 0xf3, 0xe2, 0x64, 0xda, 0x6c, 0x3d, 0xfa, 0x09, 0xfc, 0x04, 0x7e, 0x04,
	0x3f, 0x87, 0xc7, 0xc5, 0x93, 0x78, 0x10, 0x69, 0x8f, 0x7e, 0x09, 0xe9, 0x64, 0x8a, 0xdd, 0x82,
	0x78, 0xd2, 0x5b, 0xde, 0x9b, 0x37, 0xef, 0xf7, 0x2f, 0x43, 0xef, 0x06, 0x2a, 0x09, 0x23, 0xe0,
	0xf3, 0x93, 0x00, 0xb4, 0xe0, 0x19, 0x62, 0x9a, 0xfb, 0x1a, 0x7d, 0xd0, 0x31, 0x28, 0x98, 0x4d,
	0xdd, 0x4c, 0xa1, 0x46, 0xd6, 0x2a, 0xc7, 0xdc, 0x72, 0xec, 0xe4, 0xb0, 0x13, 0x61, 0x84, 0xe6,
	0x88, 0xaf, 0xbf, 0xca, 0xa9, 0xc3, 0xdb, 0x11, 0x62, 0x94, 0x02, 0x37, 0x55, 0x30, 0x3b, 0xe7,
	0x42, 0x2e, 0xca, 0xa3, 0xfe, 0x47, 0x42, 0x9b, 0x2f, 0x45, 0xfa, 0x0c, 0xf4, 0x59, 0x2c, 0x64,
	0x04, 0xec, 0x2d, 0xbd, 0x2e, 0xc2, 0x50, 0x41, 0x9e, 0x77, 0x49, 0x8f, 0x0c, 0x1a, 0xa7, 0x1d,
	0xb7, 0xbc, 0xed, 0x6e, 0x6e, 0xbb, 0x43, 0xb9, 0x18, 0x0d, 0xbf, 0x7d, 0xbf, 0xf3, 0x30, 0x4a,
	0x74, 0x3c, 0x0b, 0xdc, 0x09, 0x4e, 0x79, 0x90, 0xe2, 0x85, 0xc8, 0xb2, 0x92, 0xe8, 0x3d, 0x09,
	0xba, 0x40, 0xf5, 0x86, 0xe7, 0xb1, 0x50, 0x10, 0x72, 0xbd, 0xc8, 0x20, 0x77, 0xc7, 0x96, 0xfa,
	0xb0, 0x5c, 0xef, 0x6d, 0x70, 0xd8, 0x11, 0xad, 0x4b, 0x28, 0xfc, 0x0c, 0x0b, 0x50, 0xdd, 0x4a,
	0x8f, 0x0c, 0xaa, 0x5e, 0x4d, 0x42, 0xf1, 0x74, 0x5d, 0xf7, 0x39, 0x6d, 0x8f, 0x9f, 0x3f, 0x1a,
	0x89, 0x54, 0xc8, 0x09, 0x58, 0x8e, 0x47, 0xb4, 0xae, 0x51, 0x8b, 0x74, 0xed, 0x86, 0x61, 0x59,
	0xf5, 0x6a, 0xa6, 0x31, 0xd6, 0x71, 0xff, 0x13, 0xa1, 0xb5, 0x57, 0x89, 0x8e, 0x43, 0x25, 0x0a,
	0xd6, 0xa2, 0x15, 0x8d, 0x66, 0xa4, 0xe9, 0x55, 0x34, 0xb2, 0x9b, 0xf4, 0x40, 0x4c, 0x71, 0x26,
	0xb5, 0xc5, 0xb1, 0x15, 0x7b, 0x47, 0x9b, 0x13, 0x4c, 0xa4, 0xbf, 0x91, 0xbe, 0xff, 0x6f, 0xa5,
	0x37, 0xd6, 0x60, 0xb6, 0xe8, 0xff, 0x24, 0xb4, 0xfd, 0x24, 0x8f, 0x46, 0x26, 0xc9, 0xf0, 0x45,
	0x16, 0x0a, 0x0d, 0xac, 0x43, 0xaf, 0x49, 0x94, 0x13, 0xb0, 0xf2, 0xca, 0x82, 0x8d, 0x68, 0x6b,
	0x2e, 0x52, 0x3f, 0x07, 0xed, 0x4f, 0x8c, 0x15, 0xdd, 0x4a, 0x6f, 0x7f, 0xd0, 0x38, 0x3d, 0x76,
	0xaf, 0xfe, 0x07, 0xee, 0x76, 0xa4, 0x5e, 0x73, 0xbe, 0x1d, 0xf0, 0x90, 0x36, 0xd6, 0x6e, 0x07,
	0xa5, 0xa3, 0x56, 0x69, 0x6f, 0x77, 0xc1, 0xae, 0xe7, 0x1e, 0x95, 0x50, 0xd8, 0x0e, 0x7b, 0x40,
	0x1b, 0x85, 0x75, 0x58, 0xa4, 0x79, 0xb7, 0x6a, 0x38, 0x74, 0x77, 0x57, 0x6c, 0x42, 0xf0, 0xb6,
	0x87, 0xfb, 0x5f, 0x08, 0xbd, 0xb5, 0xab, 0xf6, 0x0c, 0xe5, 0x79, 0xa2, 0xa6, 0x7f, 0x10, 0x7d,
	0x4c, 0xeb, 0x79, 0x12, 0x49, 0xa1, 0x67, 0x0a, 0x4c, 0x6c, 0x4d, 0xef, 0x77, 0x83, 0xbd, 0x27,
	0xb4, 0xbd, 0x79, 0x14, 0xff, 0x2b, 0xbe, 0x1b, 0x70, 0xb5, 0x31, 0x7a, 0xfc, 0x79, 0xe9, 0x90,
	0xcb, 0xa5, 0x43, 0x7e, 0x2c, 0x1d, 0xf2, 0x61, 0xe5, 0xec, 0x5d, 0xae, 0x9c, 0xbd, 0xaf, 0x2b,
	0x67, 0xef, 0x35, 0xff, 0x2b, 0xd2, 0x05, 0xb7, 0x4f, 0xdd, 0x60, 0x05, 0x07, 0x86, 0xec, 0xfd,
	0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x81, 0xc5, 0x92, 0x58, 0x01, 0x04, 0x00, 0x00,
}

func (m *ValSetChange) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValSetChange) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValSetChange) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NewPower != 0 {
		i = encodeVarintPoolsToEthereum(dAtA, i, uint64(m.NewPower))
		i--
		dAtA[i] = 0x10
	}
	if m.Address != nil {
		{
			size := m.Address.Size()
			i -= size
			if _, err := m.Address.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintPoolsToEthereum(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ETHBalanceChange) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ETHBalanceChange) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ETHBalanceChange) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TotalEth != 0 {
		i = encodeVarintPoolsToEthereum(dAtA, i, uint64(m.TotalEth))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Withdraw) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Withdraw) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Withdraw) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CoinAddress != nil {
		{
			size := m.CoinAddress.Size()
			i -= size
			if _, err := m.CoinAddress.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintPoolsToEthereum(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Amount != 0 {
		i = encodeVarintPoolsToEthereum(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.To) > 0 {
		i -= len(m.To)
		copy(dAtA[i:], m.To)
		i = encodeVarintPoolsToEthereum(dAtA, i, uint64(len(m.To)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBridgedUpdate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBridgedUpdate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBridgedUpdate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Withdrawals) > 0 {
		for iNdEx := len(m.Withdrawals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Withdrawals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPoolsToEthereum(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.NewBalance != nil {
		{
			size, err := m.NewBalance.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPoolsToEthereum(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ValSetChange) > 0 {
		for iNdEx := len(m.ValSetChange) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValSetChange[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPoolsToEthereum(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Nonce != 0 {
		i = encodeVarintPoolsToEthereum(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgBridgedUpdateConfirm) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBridgedUpdateConfirm) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBridgedUpdateConfirm) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EthereumAddress != nil {
		{
			size := m.EthereumAddress.Size()
			i -= size
			if _, err := m.EthereumAddress.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintPoolsToEthereum(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintPoolsToEthereum(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x12
	}
	if m.Nonce != 0 {
		i = encodeVarintPoolsToEthereum(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPoolsToEthereum(dAtA []byte, offset int, v uint64) int {
	offset -= sovPoolsToEthereum(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ValSetChange) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Address != nil {
		l = m.Address.Size()
		n += 1 + l + sovPoolsToEthereum(uint64(l))
	}
	if m.NewPower != 0 {
		n += 1 + sovPoolsToEthereum(uint64(m.NewPower))
	}
	return n
}

func (m *ETHBalanceChange) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TotalEth != 0 {
		n += 1 + sovPoolsToEthereum(uint64(m.TotalEth))
	}
	return n
}

func (m *Withdraw) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.To)
	if l > 0 {
		n += 1 + l + sovPoolsToEthereum(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovPoolsToEthereum(uint64(m.Amount))
	}
	if m.CoinAddress != nil {
		l = m.CoinAddress.Size()
		n += 1 + l + sovPoolsToEthereum(uint64(l))
	}
	return n
}

func (m *MsgBridgedUpdate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Nonce != 0 {
		n += 1 + sovPoolsToEthereum(uint64(m.Nonce))
	}
	if len(m.ValSetChange) > 0 {
		for _, e := range m.ValSetChange {
			l = e.Size()
			n += 1 + l + sovPoolsToEthereum(uint64(l))
		}
	}
	if m.NewBalance != nil {
		l = m.NewBalance.Size()
		n += 1 + l + sovPoolsToEthereum(uint64(l))
	}
	if len(m.Withdrawals) > 0 {
		for _, e := range m.Withdrawals {
			l = e.Size()
			n += 1 + l + sovPoolsToEthereum(uint64(l))
		}
	}
	return n
}

func (m *MsgBridgedUpdateConfirm) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Nonce != 0 {
		n += 1 + sovPoolsToEthereum(uint64(m.Nonce))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovPoolsToEthereum(uint64(l))
	}
	if m.EthereumAddress != nil {
		l = m.EthereumAddress.Size()
		n += 1 + l + sovPoolsToEthereum(uint64(l))
	}
	return n
}

func sovPoolsToEthereum(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPoolsToEthereum(x uint64) (n int) {
	return sovPoolsToEthereum(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ValSetChange) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPoolsToEthereum
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValSetChange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValSetChange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolsToEthereum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Address == nil {
				m.Address = &github_com_bloxapp_pools_network_shared_types.EthereumAddress{}
			}
			if err := m.Address.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewPower", wireType)
			}
			m.NewPower = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolsToEthereum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NewPower |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPoolsToEthereum(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ETHBalanceChange) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPoolsToEthereum
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ETHBalanceChange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ETHBalanceChange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalEth", wireType)
			}
			m.TotalEth = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolsToEthereum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalEth |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPoolsToEthereum(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Withdraw) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPoolsToEthereum
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Withdraw: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Withdraw: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolsToEthereum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.To = append(m.To[:0], dAtA[iNdEx:postIndex]...)
			if m.To == nil {
				m.To = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolsToEthereum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinAddress", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolsToEthereum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CoinAddress == nil {
				m.CoinAddress = &github_com_bloxapp_pools_network_shared_types.EthereumAddress{}
			}
			if err := m.CoinAddress.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPoolsToEthereum(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBridgedUpdate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPoolsToEthereum
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBridgedUpdate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBridgedUpdate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolsToEthereum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValSetChange", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolsToEthereum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValSetChange = append(m.ValSetChange, &ValSetChange{})
			if err := m.ValSetChange[len(m.ValSetChange)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewBalance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolsToEthereum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NewBalance == nil {
				m.NewBalance = &ETHBalanceChange{}
			}
			if err := m.NewBalance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Withdrawals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolsToEthereum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Withdrawals = append(m.Withdrawals, &Withdraw{})
			if err := m.Withdrawals[len(m.Withdrawals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPoolsToEthereum(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBridgedUpdateConfirm) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPoolsToEthereum
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBridgedUpdateConfirm: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBridgedUpdateConfirm: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolsToEthereum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolsToEthereum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EthereumAddress", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolsToEthereum
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EthereumAddress == nil {
				m.EthereumAddress = &github_com_bloxapp_pools_network_shared_types.EthereumAddress{}
			}
			if err := m.EthereumAddress.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPoolsToEthereum(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPoolsToEthereum
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPoolsToEthereum(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPoolsToEthereum
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPoolsToEthereum
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPoolsToEthereum
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPoolsToEthereum
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPoolsToEthereum
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPoolsToEthereum
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPoolsToEthereum        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPoolsToEthereum          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPoolsToEthereum = fmt.Errorf("proto: unexpected end of group")
)
