// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: poolsnetwork/v1beta/pools.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Pool struct {
	Id         uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Eth2Pubkey []byte   `protobuf:"bytes,2,opt,name=eth2_pubkey,json=eth2Pubkey,proto3" json:"eth2_pubkey,omitempty"`
	Balance    uint64   `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Exited     bool     `protobuf:"varint,4,opt,name=exited,proto3" json:"exited,omitempty"`
	Slashed    bool     `protobuf:"varint,5,opt,name=slashed,proto3" json:"slashed,omitempty"`
	Committee  []uint64 `protobuf:"varint,6,rep,packed,name=committee,proto3" json:"committee,omitempty"`
}

func (m *Pool) Reset()         { *m = Pool{} }
func (m *Pool) String() string { return proto.CompactTextString(m) }
func (*Pool) ProtoMessage()    {}
func (*Pool) Descriptor() ([]byte, []int) {
	return fileDescriptor_0019268bcca18319, []int{0}
}
func (m *Pool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Pool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Pool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Pool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pool.Merge(m, src)
}
func (m *Pool) XXX_Size() int {
	return m.Size()
}
func (m *Pool) XXX_DiscardUnknown() {
	xxx_messageInfo_Pool.DiscardUnknown(m)
}

var xxx_messageInfo_Pool proto.InternalMessageInfo

func (m *Pool) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Pool) GetEth2Pubkey() []byte {
	if m != nil {
		return m.Eth2Pubkey
	}
	return nil
}

func (m *Pool) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Pool) GetExited() bool {
	if m != nil {
		return m.Exited
	}
	return false
}

func (m *Pool) GetSlashed() bool {
	if m != nil {
		return m.Slashed
	}
	return false
}

func (m *Pool) GetCommittee() []uint64 {
	if m != nil {
		return m.Committee
	}
	return nil
}

func init() {
	proto.RegisterType((*Pool)(nil), "poolsnetwork.v1beta1.Pool")
}

func init() { proto.RegisterFile("poolsnetwork/v1beta/pools.proto", fileDescriptor_0019268bcca18319) }

var fileDescriptor_0019268bcca18319 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x31, 0x4e, 0xc3, 0x30,
	0x14, 0x86, 0xe3, 0x34, 0x04, 0x30, 0x88, 0xc1, 0x42, 0xc8, 0x03, 0x72, 0x23, 0xa6, 0x2c, 0x24,
	0x2a, 0x88, 0x0b, 0x70, 0x01, 0xaa, 0x8c, 0x2c, 0xc8, 0x4e, 0x9e, 0x88, 0x55, 0xa7, 0xcf, 0x6a,
	0x5c, 0x48, 0x6f, 0xc1, 0x15, 0xb8, 0x0d, 0x63, 0x47, 0x46, 0x94, 0x5c, 0x04, 0xd5, 0x25, 0x02,
	0xc6, 0xff, 0x7b, 0xff, 0x3f, 0xbc, 0x8f, 0x4e, 0x2d, 0xa2, 0x69, 0x97, 0xe0, 0x5e, 0x71, 0xb5,
	0xc8, 0x5f, 0x66, 0x0a, 0x9c, 0xcc, 0x3d, 0xcb, 0xec, 0x0a, 0x1d, 0xb2, 0xf3, 0xbf, 0x85, 0x6c,
	0x5f, 0x98, 0x5d, 0xbd, 0x13, 0x1a, 0xcd, 0x11, 0x0d, 0x3b, 0xa3, 0xa1, 0xae, 0x38, 0x49, 0x48,
	0x1a, 0x15, 0xa1, 0xae, 0xd8, 0x94, 0x9e, 0x80, 0xab, 0x6f, 0x9e, 0xec, 0x5a, 0x2d, 0x60, 0xc3,
	0xc3, 0x84, 0xa4, 0xa7, 0x05, 0xdd, 0xa1, 0xb9, 0x27, 0x8c, 0xd3, 0x43, 0x25, 0x8d, 0x5c, 0x96,
	0xc0, 0x27, 0x7e, 0x35, 0x46, 0x76, 0x41, 0x63, 0xe8, 0xb4, 0x83, 0x8a, 0x47, 0x09, 0x49, 0x8f,
	0x8a, 0x9f, 0xb4, 0x5b, 0xb4, 0x46, 0xb6, 0x35, 0x54, 0xfc, 0xc0, 0x1f, 0xc6, 0xc8, 0x2e, 0xe9,
	0x71, 0x89, 0x4d, 0xa3, 0x9d, 0x03, 0xe0, 0x71, 0x32, 0x49, 0xa3, 0xe2, 0x17, 0xdc, 0x3f, 0x7c,
	0xf4, 0x82, 0x6c, 0x7b, 0x41, 0xbe, 0x7a, 0x41, 0xde, 0x06, 0x11, 0x6c, 0x07, 0x11, 0x7c, 0x0e,
	0x22, 0x78, 0xbc, 0x7b, 0xd6, 0xae, 0x5e, 0xab, 0xac, 0xc4, 0x26, 0x57, 0x06, 0x3b, 0x69, 0xed,
	0xfe, 0xe7, 0xeb, 0x51, 0x44, 0x97, 0xff, 0xf3, 0xe2, 0x36, 0x16, 0x5a, 0x15, 0x7b, 0x23, 0xb7,
	0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7d, 0xd5, 0xf6, 0x3f, 0x34, 0x01, 0x00, 0x00,
}

func (m *Pool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Pool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Pool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Committee) > 0 {
		dAtA2 := make([]byte, len(m.Committee)*10)
		var j1 int
		for _, num := range m.Committee {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintPools(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x32
	}
	if m.Slashed {
		i--
		if m.Slashed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.Exited {
		i--
		if m.Exited {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.Balance != 0 {
		i = encodeVarintPools(dAtA, i, uint64(m.Balance))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Eth2Pubkey) > 0 {
		i -= len(m.Eth2Pubkey)
		copy(dAtA[i:], m.Eth2Pubkey)
		i = encodeVarintPools(dAtA, i, uint64(len(m.Eth2Pubkey)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintPools(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPools(dAtA []byte, offset int, v uint64) int {
	offset -= sovPools(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Pool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovPools(uint64(m.Id))
	}
	l = len(m.Eth2Pubkey)
	if l > 0 {
		n += 1 + l + sovPools(uint64(l))
	}
	if m.Balance != 0 {
		n += 1 + sovPools(uint64(m.Balance))
	}
	if m.Exited {
		n += 2
	}
	if m.Slashed {
		n += 2
	}
	if len(m.Committee) > 0 {
		l = 0
		for _, e := range m.Committee {
			l += sovPools(uint64(e))
		}
		n += 1 + sovPools(uint64(l)) + l
	}
	return n
}

func sovPools(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPools(x uint64) (n int) {
	return sovPools(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Pool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPools
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Pool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Pool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Eth2Pubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthPools
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthPools
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Eth2Pubkey = append(m.Eth2Pubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.Eth2Pubkey == nil {
				m.Eth2Pubkey = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			m.Balance = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Balance |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exited", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Exited = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slashed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPools
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Slashed = bool(v != 0)
		case 6:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPools
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Committee = append(m.Committee, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowPools
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthPools
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthPools
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Committee) == 0 {
					m.Committee = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowPools
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Committee = append(m.Committee, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Committee", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPools(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthPools
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthPools
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPools(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPools
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPools
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPools
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPools
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPools
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPools
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPools        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPools          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPools = fmt.Errorf("proto: unexpected end of group")
)
